services:
  
  db:
    image: postgres:16
    container_name: smartmeetingroom-db

    # Load secrets from .env.secrets into the container
    env_file:
      - .env.secrets

    # Use those variables inside the container
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped


    networks: [appnet]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartuser -d smartmeetingroom"]
      interval: 5s
      timeout: 5s
      retries: 20

  db_init:
    build:
      context: .
      dockerfile: Dockerfile.db_init
    container_name: db-init
    environment:
      DATABASE_URL: ${DATABASE_URL}

    
    depends_on:
      db:
        condition: service_healthy   # âœ… wait for DB really ready
    command: ["python", "db_init.py"]
    restart: "no"
    networks: [appnet]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks: [appnet]

  users_service:
    build:
      context: .
      dockerfile: services/users_service/Dockerfile
    container_name: users-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8001:8000"
    depends_on:
      db_init:
        condition: service_completed_successfully
    restart: unless-stopped
    networks: [appnet]

  # --------- ROOMS: replicated instances (no host ports) ---------
  rooms_service_1:
    build:
      context: .
      dockerfile: services/rooms_service/Dockerfile
    container_name: rooms-service-1
    environment:
      DATABASE_URL: ${DATABASE_URL}
    expose:
      - "8000"

    depends_on:
      db_init:
        condition: service_completed_successfully
    restart: unless-stopped
    networks: [appnet]

  rooms_service_2:
    build:
      context: .
      dockerfile: services/rooms_service/Dockerfile
    container_name: rooms-service-2
    environment:
      DATABASE_URL: ${DATABASE_URL}
    expose:
      - "8000"

    depends_on:
      db_init:
        condition: service_completed_successfully
    restart: unless-stopped
    networks: [appnet]

  # --------- NGINX gateway for rooms load balancing ---------
  nginx_rooms:
    image: nginx:alpine
    container_name: nginx-rooms-lb
    ports:
      - "8002:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rooms_service_1
      - rooms_service_2
    restart: unless-stopped
    networks: [appnet]

  bookings_service:
    build:
      context: .
      dockerfile: services/bookings_service/Dockerfile
    container_name: bookings-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_HOST: ${RABBITMQ_HOST}



    ports:
      - "8003:8000"
    depends_on:
      db_init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks: [appnet]

  reviews_service:
    build:
      context: .
      dockerfile: services/reviews_service/Dockerfile
    container_name: reviews-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_HOST: ${RABBITMQ_HOST}

    
    
    ports:
      - "8004:8000"
    depends_on:
      db_init:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks: [appnet]

  # --------- NEW: global HTTPS reverse proxy ---------
  nginx:
    image: nginx:alpine
    container_name: smartmeetingroom-nginx
    depends_on:
      - users_service
      - rooms_service_1
      - rooms_service_2
      - bookings_service
      - reviews_service
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx_https.conf:/etc/nginx/nginx.conf:ro    # <-- change to this
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - appnet


volumes:
  db_data:

networks:
  appnet:
    driver: bridge
