services:
  db:
    image: postgres:16
    container_name: smartmeetingroom-db
    environment:
      POSTGRES_DB: smartmeetingroom
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartpass
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ protocol
      - "15672:15672"  # Web UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  users_service:
    build:
      context: .
      dockerfile: services/users_service/Dockerfile
    container_name: users-service
    environment:
      DATABASE_URL: postgresql+psycopg2://smartuser:smartpass@db:5432/smartmeetingroom
    ports:
      - "8001:8000"
    depends_on:
      - db
    restart: unless-stopped

  rooms_service:
    build:
      context: .
      dockerfile: services/rooms_service/Dockerfile
    container_name: rooms-service
    environment:
      DATABASE_URL: postgresql+psycopg2://smartuser:smartpass@db:5432/smartmeetingroom
    ports:
      - "8002:8000"
    depends_on:
      - db
    restart: unless-stopped

  bookings_service:
    build:
      context: .
      dockerfile: services/bookings_service/Dockerfile
    container_name: bookings-service
    environment:
      DATABASE_URL: postgresql+psycopg2://smartuser:smartpass@db:5432/smartmeetingroom
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8003:8000"
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  reviews_service:
    build:
      context: .
      dockerfile: services/reviews_service/Dockerfile
    container_name: reviews-service
    environment:
      DATABASE_URL: postgresql+psycopg2://smartuser:smartpass@db:5432/smartmeetingroom
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8004:8000"
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data:
